{{
  //pre request script
  const date = new Date();
  exports.startDate = date.toString();
  exports.endDate = date.toString();
}}
GET  http://localhost:3000/posts/
  ?limit=1
  &page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoibWFyazFAZG9lLmNvbSIsImlhdCI6MTc2MDM1MzM3OCwiZXhwIjoxNzYwMzU2OTc4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.MYtpde8DRYHV7D-yORid0LJvwtg0oKj1twF82Kz6_kQ

